# Generated by Django 5.1.3 on 2024-12-08 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('League', '0001_initial'),
        ('Teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teams',
            name='league',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='League.league'),
        ),
        migrations.AddField(
            model_name='teams',
            name='stadium',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='teams',
            name='stadium_capacity',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
