# Generated by Django 5.1.3 on 2024-12-14 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Teams', '0002_teams_league_teams_stadium_teams_stadium_capacity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teams',
            options={'verbose_name_plural': 'Teams'},
        ),
    ]
