# Generated by Django 5.1.3 on 2024-12-08 18:21

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('league_name', models.CharField(max_length=64)),
                ('number_of_teams', models.PositiveSmallIntegerField()),
                ('country', django_countries.fields.CountryField(max_length=2)),
            ],
        ),
    ]
