# Generated by Django 5.1.3 on 2024-12-14 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('League', '0002_league_league_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='league_logo',
            field=models.ImageField(blank=True, null=True, upload_to='league_logos/'),
        ),
    ]
