# Generated by Django 5.1.4 on 2024-12-15 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('League', '0003_alter_league_league_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='top5_league',
            field=models.BooleanField(default=False, verbose_name='Top-5 League'),
        ),
    ]
