# Generated by Django 5.1.4 on 2024-12-15 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('League', '0004_league_top5_league'),
    ]

    operations = [
        migrations.RenameField(
            model_name='league',
            old_name='top5_league',
            new_name='is_top5_league',
        ),
    ]
