# Generated by Django 5.1.3 on 2024-11-26 17:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=64)),
                ('position', models.CharField(choices=[('ATT', 'Attacker'), ('MID', 'Midfielder'), ('DEF', 'Defender'), ('GK', 'Goalkeeper')], max_length=3)),
                ('shirt_number', models.PositiveIntegerField(max_length=3)),
                ('height', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(150)])),
            ],
        ),
    ]
