# Generated by Django 5.1.2 on 2024-12-07 21:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Players', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=64)),
                ('position', models.CharField(choices=[('ATT', 'Attacker'), ('MID', 'Midfielder'), ('DEF', 'Defender'), ('GK', 'Goalkeeper')], max_length=3)),
                ('shirt_number', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(150)])),
                ('preffered_foot', models.CharField(choices=[('R', 'Right'), ('L', 'Left'), ('B', 'Both')], max_length=2)),
            ],
        ),
        migrations.DeleteModel(
            name='Player',
        ),
    ]
