# Generated by Django 5.1.2 on 2024-12-07 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Players', '0003_position_remove_players_position_subposition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subposition',
            name='position',
        ),
        migrations.RemoveField(
            model_name='players',
            name='shirt_number',
        ),
        migrations.AddField(
            model_name='players',
            name='position',
            field=models.CharField(choices=[('ATT', 'Attacker'), ('MID', 'Midfielder'), ('DEF', 'Defender'), ('GK', 'Goalkeeper')], default='Midfielder', max_length=3),
        ),
        migrations.DeleteModel(
            name='Position',
        ),
        migrations.DeleteModel(
            name='SubPosition',
        ),
    ]
