# Generated by Django 5.1.2 on 2024-12-07 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Players', '0005_remove_players_preffered_foot_players_preferred_foot_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='players',
            options={'verbose_name': 'Players'},
        ),
    ]
