# Generated by Django 5.1.3 on 2024-12-14 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Players', '0007_alter_players_options_players_team'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='players',
            options={'verbose_name_plural': 'Players'},
        ),
        migrations.AddField(
            model_name='players',
            name='player_photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
