# Generated by Django 5.1.3 on 2024-12-14 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Players', '0008_alter_players_options_players_player_photo'),
        ('Teams', '0004_teams_club_logo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Players',
            new_name='Player',
        ),
        migrations.AlterModelOptions(
            name='player',
            options={'verbose_name': 'Player', 'verbose_name_plural': 'Players'},
        ),
    ]
